name: Node.js CI Windows build and test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:

    # Run the workflow on the latest Windows environment
    runs-on: windows-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'  # Enables caching of npm dependencies

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

      # Step 5: Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Using the secret token for authentication
        files: ./coverage/test-coverage.xml  # Path to the XML report
        fail_ci_if_error: true  # Fail the CI if uploading fails
        verbose: true  # Show details about the upload process

